/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ตัวตนของผู้ใช้ที่ login อยู่ (จาก token ที่ตรวจแล้ว) */
        get: operations["MeController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ตรวจสถานะระบบ (สาธารณะ) */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/office-hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** เวลาทำการรายสัปดาห์ของอาจารย์ (กรองด้วย teacherCoreUserId) */
        get: operations["OfficeHoursController_findAll"];
        put?: never;
        /** เพิ่มเวลาทำการของตัวเอง */
        post: operations["OfficeHoursController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/office-hours/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** ลบเวลาทำการ */
        delete: operations["OfficeHoursController_remove"];
        options?: never;
        head?: never;
        /** แก้ไขเวลาทำการ */
        patch: operations["OfficeHoursController_update"];
        trace?: never;
    };
    "/api/v1/booking-exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** รายการเปิด/ปิดเวลาเฉพาะวันของอาจารย์ */
        get: operations["BookingExceptionsController_findAll"];
        put?: never;
        /** เปิดหรือปิดเวลาเฉพาะช่วงของตัวเอง */
        post: operations["BookingExceptionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/booking-exceptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** ยกเลิกรายการเปิด/ปิดเวลา (ย้อนกลับไปใช้เวลาทำการรายสัปดาห์) */
        delete: operations["BookingExceptionsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** คิวนัดหมายของฉัน (อาจารย์เห็นคิวที่ตัวเองดูแล นักศึกษาเห็นคิวของตัวเอง) */
        get: operations["BookingsController_findAll"];
        put?: never;
        /** อาจารย์สร้างนัดหมายให้นักศึกษาในคิวของตัวเอง */
        post: operations["BookingsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ดูนัดหมายรายการเดียว */
        get: operations["BookingsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** ยกเลิกนัดหมาย (ช่วงเวลากลับไปว่าง) */
        patch: operations["BookingsController_cancel"];
        trace?: never;
    };
    "/api/v1/bookings/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** ทำเครื่องหมายว่านัดหมายเสร็จสิ้น */
        patch: operations["BookingsController_complete"];
        trace?: never;
    };
    "/api/v1/chat-messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ข้อความในนัดหมายหนึ่งรายการ (เก่า → ใหม่) */
        get: operations["ChatMessagesController_findAll"];
        put?: never;
        /** ส่งข้อความในนัดหมายของตัวเอง */
        post: operations["ChatMessagesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat-messages/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** ทำเครื่องหมายว่าอ่านข้อความแล้ว */
        patch: operations["ChatMessagesController_markRead"];
        trace?: never;
    };
    "/api/v1/schedule-slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ช่วงนัดของอาจารย์ในสัปดาห์หนึ่ง (จันทร์-ศุกร์) เรียงตามเวลา — ส่ง limit=100 เพื่อได้ทั้งสัปดาห์ */
        get: operations["ScheduleController_findSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teachers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** อาจารย์ที่เปิดเวลาทำการแล้ว (ใช้เลือกดูตาราง) */
        get: operations["TeachersController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PaginationMetaModel: {
            /** @example 42 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            limit: number;
            /** @example 3 */
            totalPages: number;
        };
        OfficeHourResponse: {
            /** Format: uuid */
            id: string;
            /** @description ค่า sub ของอาจารย์เจ้าของเวลา */
            teacherCoreUserId: string;
            /** @description รหัสบุคลากรจาก Core Hub (แสดงแทนชื่อ) */
            teacherPersonCode: string | null;
            /** @enum {string} */
            dayOfWeek: "MON" | "TUE" | "WED" | "THU" | "FRI";
            /**
             * @description เวลาท้องถิ่น Asia/Bangkok รูปแบบ HH:mm
             * @example 09:00
             */
            startTime: string;
            /** @example 12:00 */
            endTime: string;
            /** @example 30 */
            slotMinutes: number;
            isAvailable: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateOfficeHourDto: {
            /**
             * @example MON
             * @enum {string}
             */
            dayOfWeek: "MON" | "TUE" | "WED" | "THU" | "FRI";
            /** @example 09:00 */
            startTime: string;
            /** @example 12:00 */
            endTime: string;
            /**
             * @description ความยาวของช่วงนัด 1 ช่วง (นาที)
             * @default 30
             */
            slotMinutes: number;
            /** @default true */
            isAvailable: boolean;
        };
        UpdateOfficeHourDto: {
            /**
             * @example MON
             * @enum {string}
             */
            dayOfWeek?: "MON" | "TUE" | "WED" | "THU" | "FRI";
            /** @example 09:00 */
            startTime?: string;
            /** @example 12:00 */
            endTime?: string;
            /**
             * @description ความยาวของช่วงนัด 1 ช่วง (นาที)
             * @default 30
             */
            slotMinutes: number;
            /** @default true */
            isAvailable: boolean;
        };
        DeletedModel: {
            /** Format: uuid */
            id: string;
            /** @example true */
            deleted: boolean;
        };
        BookingExceptionResponse: {
            /** Format: uuid */
            id: string;
            teacherCoreUserId: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** @enum {string} */
            status: "AVAILABLE" | "UNAVAILABLE";
            reason: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateBookingExceptionDto: {
            /**
             * Format: date-time
             * @example 2026-10-05T12:00:00+07:00
             */
            startsAt: string;
            /**
             * Format: date-time
             * @example 2026-10-05T13:00:00+07:00
             */
            endsAt: string;
            /**
             * @description AVAILABLE = เปิดเวลานี้ให้จอง · UNAVAILABLE = ปิดเวลานี้
             * @enum {string}
             */
            status: "AVAILABLE" | "UNAVAILABLE";
            reason?: string;
        };
        BookingResponse: {
            /** Format: uuid */
            id: string;
            /** @description ค่า sub ของอาจารย์ */
            teacherCoreUserId: string;
            /** @description รหัสบุคลากรจาก Core Hub (แสดงแทนชื่อ) */
            teacherPersonCode: string | null;
            /** @description ค่า sub ของนักศึกษา */
            studentCoreUserId: string;
            /** @description รหัสนักศึกษาจาก Core Hub (แสดงแทนชื่อ) */
            studentPersonCode: string | null;
            /** @description ชื่อนักศึกษา อ่านจาก Core Hub ตอนเปิดดูรายการเดียวและเฉพาะผู้ที่มีสิทธิ์อ่านข้อมูลบุคคล — ไม่เก็บในฐานข้อมูล */
            studentFullNameTh: string | null;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            topic: string;
            /** @enum {string} */
            status: "CONFIRMED" | "CANCELLED" | "COMPLETED";
            /** @description จำนวนข้อความในคิวนี้ที่อีกฝ่ายส่งมาและยังไม่ได้อ่าน */
            unreadCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateBookingDto: {
            /** @example 6704101312 */
            studentPersonCode: string;
            /**
             * Format: date-time
             * @example 2026-10-12T09:00:00+07:00
             */
            startsAt: string;
            /**
             * Format: date-time
             * @example 2026-10-12T09:30:00+07:00
             */
            endsAt: string;
            /** @example ปรึกษาโครงงานพิเศษ */
            topic: string;
        };
        ChatMessageResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            bookingId: string;
            /** @description ค่า sub ของผู้ส่ง — เทียบกับ id จาก GET /api/v1/me เพื่อรู้ว่าเป็นข้อความของเราหรือไม่ */
            senderCoreUserId: string;
            message: string;
            isRead: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        CreateChatMessageDto: {
            /** Format: uuid */
            bookingId: string;
            /** @example สวัสดี ขอเลื่อนนัดได้ไหม */
            message: string;
        };
        SlotBookingModel: {
            /** Format: uuid */
            id: string;
            /** @description รหัสนักศึกษา (แสดงแทนชื่อ) */
            studentPersonCode: string | null;
            topic: string;
            /** @enum {string} */
            status: "CONFIRMED" | "CANCELLED" | "COMPLETED";
        };
        ScheduleSlotResponse: {
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** @enum {string} */
            status: "AVAILABLE" | "BOOKED";
            /** @description นัดหมายในช่วงนี้เป็นของผู้เรียกเอง */
            bookedByMe: boolean;
            /** @description รายละเอียดนัดหมาย — เห็นเฉพาะอาจารย์เจ้าของตารางและผู้ดูแลระบบ คนอื่นเห็นแค่ว่าไม่ว่าง */
            booking: components["schemas"]["SlotBookingModel"] | null;
        };
        TeacherResponse: {
            /** @description ค่า sub ของอาจารย์ — ใช้เป็น teacherCoreUserId ในคำขออื่น */
            coreUserId: string;
            /** @description รหัสบุคลากรจาก Core Hub (แสดงแทนชื่อ) */
            personCode: string | null;
        };
        HealthModel: {
            /** @example ok */
            status: string;
            /** @example csmju-q-teacher */
            service: string;
        };
        MeModel: {
            /** @description ค่า sub ของผู้ใช้ใน Core Hub (ไม่ใช่ UUID เสมอไป) */
            id: string;
            /** @description ใช้แสดงผลเท่านั้น ห้ามใช้เป็นกุญแจ */
            email: string;
            /** @example lecturer */
            coreRole: string;
            /** @enum {string} */
            subsystemRole: "STUDENT" | "TEACHER" | "ADMIN";
            session: {
                /** Format: date-time */
                expiresAt: string | null;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    MeController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["MeModel"];
                    };
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["HealthModel"];
                    };
                };
            };
        };
    };
    OfficeHoursController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description ค่า sub ของอาจารย์ (ไม่ใช่ UUID เสมอไป) */
                teacherCoreUserId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["OfficeHourResponse"][];
                        meta: components["schemas"]["PaginationMetaModel"];
                    };
                };
            };
        };
    };
    OfficeHoursController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOfficeHourDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["OfficeHourResponse"];
                    };
                };
            };
        };
    };
    OfficeHoursController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["DeletedModel"];
                    };
                };
            };
        };
    };
    OfficeHoursController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOfficeHourDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["OfficeHourResponse"];
                    };
                };
            };
        };
    };
    BookingExceptionsController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description ค่า sub ของอาจารย์ (ไม่ใช่ UUID เสมอไป) */
                teacherCoreUserId?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["BookingExceptionResponse"][];
                        meta: components["schemas"]["PaginationMetaModel"];
                    };
                };
            };
        };
    };
    BookingExceptionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingExceptionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["BookingExceptionResponse"];
                    };
                };
            };
        };
    };
    BookingExceptionsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["DeletedModel"];
                    };
                };
            };
        };
    };
    BookingsController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                status?: "CONFIRMED" | "CANCELLED" | "COMPLETED";
                from?: string;
                to?: string;
                sort?: "startsAt" | "-startsAt" | "-createdAt";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["BookingResponse"][];
                        meta: components["schemas"]["PaginationMetaModel"];
                    };
                };
            };
        };
    };
    BookingsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["BookingResponse"];
                    };
                };
            };
        };
    };
    BookingsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["BookingResponse"];
                    };
                };
            };
        };
    };
    BookingsController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["BookingResponse"];
                    };
                };
            };
        };
    };
    BookingsController_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["BookingResponse"];
                    };
                };
            };
        };
    };
    ChatMessagesController_findAll: {
        parameters: {
            query: {
                page?: number;
                limit?: number;
                /** @description นัดหมายที่ต้องการอ่านข้อความ */
                bookingId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ChatMessageResponse"][];
                        meta: components["schemas"]["PaginationMetaModel"];
                    };
                };
            };
        };
    };
    ChatMessagesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChatMessageDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ChatMessageResponse"];
                    };
                };
            };
        };
    };
    ChatMessagesController_markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ChatMessageResponse"];
                    };
                };
            };
        };
    };
    ScheduleController_findSlots: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description ค่า sub ของอาจารย์ (ไม่ใช่ UUID เสมอไป) — อาจารย์ไม่ระบุ = ตารางของตัวเอง */
                teacherCoreUserId?: string;
                /** @description วันใดก็ได้ในสัปดาห์ที่ต้องการ (วันนี้ถ้าไม่ระบุ) */
                weekStart?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ScheduleSlotResponse"][];
                        meta: components["schemas"]["PaginationMetaModel"];
                    };
                };
            };
        };
    };
    TeachersController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["TeacherResponse"][];
                        meta: components["schemas"]["PaginationMetaModel"];
                    };
                };
            };
        };
    };
}
